services:
  # --- The Classifier Service ---
  classifier-service:
    image: 24archit/ai-crm/classifier_service
    container_name: crm_classifier_service
    ports:
      - "8000:8000"
    restart: unless-stopped

  # --- The RAG & Summarization Service ---
  rag-service:
    image: 24archit/ai-crm/rag_service
    container_name: crm_rag_service
    ports:
      - "8001:8001"
    env_file:
      - ./rag_service/.env
    restart: unless-stopped

        

